### ISSUE TITLE
Plugin meta pass

### ISSUE THREAD

**Issue by willmot** [humanmade/mad-mimi-sign-up-forms-wordpress-plugin#14]
Let's take this opportunity to update any of the plugin meta that needs changing.

Here's what we have now

``` PHP
/*
Plugin Name: Mad Mimi Sign Up Forms
Plugin URI: http://wordpress.org/extend/plugins/madmimi/
Description: The Official Mad Mimi plugin allows your site visitors to subscribe to your email lists
Author: Mad Mimi, LLC
Version: 1.2
Author URI: http://madmimi.com/
License: GPLv2 or later

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
```

**Comment by willmot** [comment]
The `Plugin URI` is actually incorrect, should be `https://wordpress.org/plugins/mad-mimi-sign-up-forms/`

Fixed in 2ae4c32

**Comment by willmot** [comment]
- [x] We need to bump the tested to version to 4.2 (in Readme)

**Comment by willmot** [comment]
@susandyoung any copy updates to the plugin description? (This is on the old plugin).

**Comment by willmot** [comment]
- [x] Update Author list to mention Human Made

**Comment by susandyoung** [comment]
@willmot I'll run this by our copy people to be sure.

**Comment by willmot** [comment]
Updated copy from @susandyoung 

> **Mad Mimi WP Plugin Copy**
> 
> What should it be officially called? Mad Mimi's is:
> - Official Mad Mimi Signup Forms
> 
> What should the plugin description be, Mad Mimi's is:
> - Add the Mad Mimi webform to your WordPress site! Easy to set up, the Mad Mimi plugin allows your site visitors to subscribe to your email lists.
> 
> Readme, Mad Mimi's is:
> - The Official Mad Mimi Signup Form plugin makes it easy to grow your subscribers! Use this plugin to integrate your sign up forms into your WordPress site. To learn more about Mad Mimi, grab a [FREE forever account](http://madmimi.com/) and explore.
>   
>   Once the plugin is activated, you can select and insert any of your Mad Mimi webforms right into your site by using a widget, shortcode, or template tag. Setup is easy; in Settings, simply enter your account email address and API key (found in your [Mad Mimi account](http://help.madmimi.com/where-can-i-find-my-api-key/)), and you're all set.
> 
> **Official Mad Mimi Forms plugin features:**
> - Automatically add new forms for users to sign up to an email list of your choice
> - Insert unlimited signup forms using the widget, shortcode, or template tag
> - Use quick links to edit and preview your form in Mad Mimi
> 
> Plugin Tags, Mad Mimi's are:
> - forms, newsletter, opt-in
> 
> Installation instructions, Mad Mimi's are:
> 1. Upload plugin files to your plugins folder, or install using WordPress' built-in Add New Plugin installer.
> 2. Activate the plugin.
> 3. Go to the plugin settings page (under Settings > Mad Mimi Settings).
> 4. Enter your account email address and API key (found in your [Mad Mimi account](http://help.madmimi.com/where-can-i-find-my-api-key/) area).
> 5. Click **Save Changes**.
> 
> After your account is verified, you can insert a form into your site by using a widget, shortcode, or template tag:
> - **Widget**
>   Go to Appearance > Widgets, find the Mad Mimi Form widget, and drag it into the widget area of your choice. You can then add a title and select a form!
> - **Shortcode**
>   Add a form to any post or page by adding the shortcode (e.g., [madmimi id=80326]) in the page/post editor. You can find a form's ID on the Mad Mimi Settings page.
> - **Template tag**
>   Add the following template tag into any WordPress file: <?php madmimi_form( $form_id ); ?>.
>   For example: <?php madmimi_form( 91 ); ?>
>   You can find a form's ID on the Mad Mimi Settings page.
> 
> That's it. You're ready to go!
> 
> FAQ
> 
> **What is Mad Mimi?**
> 
> [Mad Mimi](https://madmimi.com/) is the easiest way to create, send, share, and track email newsletters online. It's for people who want email marketing to be simple.
> 
> **Do I need a Mad Mimi account to use this plugin?**
> 
> Yes, this plugin requires a [Mad Mimi](https://madmimi.com/) account.
> 
> **Is there a widget?**
> 
> Absolutely. Use it by finding the Mad Mimi Form widget under Appearance >Widgets in the WordPress Dashboard and dragging it into the widget area of your choice. You can then add a title and select a form!
> 
> **Is there a shortcode?**
> 
> Yes! You can add a form to any post or page by adding the shortcode with the form ID (ex. [madmimi id=80326]) in the page/post editor. Form IDs are listed on the Mad Mimi Settings page.
> 
> **Is there a template tag?**
> 
> Yup! Add the following template tag into any WordPress file: <?php madmimi_form( $form_id ); ?>. For example: <?php madmimi_form( 91 ); ?>. Form IDs are listed on the Mad Mimi Settings page.
> 
> **Where can I find the API Key?**
> 
> The API key is in your Mad Mimi account area. For more details see: [http://help.madmimi.com/where-can-i-find-my-api-key/](http://help.madmimi.com/where-can-i-find-my-api-key/)
> - Screenshots: need updating once new plugin is done.
> - Changelog: should mention it's forked from Mad Mimi
> - Plugin Authors: Mad Mimi Plugin currently lists
> - Mad Mimi Email Marketing
> - illuminea
> - Maor Chasen
> - Rebecca Markowitz
> 
> I'm thinking that for this new version it will want to be
> - GoDaddy
> - Human Made

**Comment by willmot** [comment]
Fixed!
