### ISSUE TITLE
Release update to plugin directory

### ISSUE THREAD

**Issue by willmot** [humanmade/mad-mimi-sign-up-forms-wordpress-plugin#19]
We'll want to
- [x] Get access to wp.org SVN
- [x] Close out other issues
- [x] Do a full round of testing
- [x] Bump the plugin version
- [x] Tag and release to .org

**Comment by willmot** [comment]
@susandyoung @saschamt are there any other changes you'd like to make as part of this update we'll be releasing for the existing plugin?

**Comment by susandyoung** [comment]
@willmot I don't believe so. Double checking on the design assets and copy.

**Comment by saschamt** [comment]
toDo looks good @willmot — @susandyoung anything to add?

**Comment by willmot** [comment]
Great thanks both

**Comment by willmot** [comment]
@susandyoung In order to release this update I'll need commit access to the plugins SVN repo on WordPress.org, is that something you could handle? My wordpress.org username is `willmot`.

**Comment by susandyoung** [comment]
This isn't something I can do. Can you add Marc Heiligers here and maybe he can jump in? His GitHub ID is @marcheiligers

**Comment by willmot** [comment]
Thanks @susandyoung. @marcheiligers would you be able to get me commit access to the Mad Mimi plugin: https://wordpress.org/plugins/mad-mimi-sign-up-forms/

Thanks!

**Comment by willmot** [comment]
We're ready to release. Will do so tomorrow

**Comment by willmot** [comment]
Finally managed to get this live, internet in spain is not so great :-1: 
\0/
