### ISSUE TITLE
Translation pass

### ISSUE THREAD

**Issue by willmot** [humanmade/mad-mimi-sign-up-forms-wordpress-plugin#6]
let's make sure all our strings are correctly marked for translation and update the POT file.

**Comment by willmot** [comment]
- [x] All strings marked for translation
- [x] All strings using correct text-domain
- [x] All translated strings properly escaped
- [x] All JS strings properly localised

**Comment by willmot** [comment]
- ~~Translate help screens~~ moved to https://github.com/humanmade/madmimi-wp/issues/15

**Comment by willmot** [comment]
>  All translated strings properly escaped

@joehoyle is this a requirement would you say?

**Comment by willmot** [comment]
- [x] Re-generate the POT - #17

**Comment by joehoyle** [comment]
Yes, especially if this is on VIP

**Comment by willmot** [comment]
👍 done in #12
