### ISSUE TITLE
Admin UI Pass

### ISSUE THREAD

**Issue by willmot** [humanmade/mad-mimi-sign-up-forms-wordpress-plugin#9]
Let's make sure the admin UI we are adding fits within the overall wp-admin style.

**Comment by willmot** [comment]
- [x] Feels like the forms table should be full-width, it's currently artificially limited to `60%` width

![screen shot 2015-05-21 at 18 49 56](https://cloud.githubusercontent.com/assets/308507/7755188/4c933344-ffea-11e4-8aae-829b465a0928.png)

which looks especially bad on mobile

![screen shot 2015-05-21 at 18 50 31](https://cloud.githubusercontent.com/assets/308507/7755189/4e6b3fd6-ffea-11e4-8874-74e812be141f.png)

**Comment by willmot** [comment]
- [x] The intro section has poor contrast and doesn't really look great amongst the rest of the admin UI

![screen shot 2015-05-21 at 18 54 56](https://cloud.githubusercontent.com/assets/308507/7755302/ff014afc-ffea-11e4-9d32-7e63669db97a.png)

**Comment by willmot** [comment]
@saschamt & @susandyoung be good to get your input here.

First are you happy with the change to switch the table which lists a users forms to full-width (plays much nicer on mobile).

Second, are there any design / copy changes you'd like to make to that intro banner? I'd be tempted to try going for something that looks more of a standard WordPress style with the mad-mimi logo for branding, rather than text overlaying the branded banner. Also happy to just leave as is if that's preferred 👍

**Comment by saschamt** [comment]
Thanks @willmot — please go full width for the table and forms. That banner should really be more minimal as you have suggested. Do you want to do the changes or do you prefer me changing the banner?

**Comment by willmot** [comment]
@saschamt I'm happy to whip up a suggestion and share here, we can iterate from there 👍

**Comment by willmot** [comment]
@saschamt apologies taken me a while to get to this.

My suggestion, we switch to the standard WordPress notice UI. I've also worked in the standard WordPress dismiss notice icon and used the standard button design for the signup now button. The major benefits here are on mobile as we benefit from all the responsive work the native WordPress UI has.

First suggestion is completely vanilla WordPress style:

![screen shot 2015-06-15 at 15 00 11](https://cloud.githubusercontent.com/assets/308507/8163532/9489218c-137b-11e5-987b-903e2e6f4423.png)
![screen shot 2015-06-15 at 15 00 03](https://cloud.githubusercontent.com/assets/308507/8163533/94ac916c-137b-11e5-8aaa-fae7563ffa70.png)

On desktop we could work in the Mad Mimi icon for some color / branding:

![screen shot 2015-06-15 at 14 59 48](https://cloud.githubusercontent.com/assets/308507/8163545/a2e55f16-137b-11e5-9606-42e0c152e89e.png)

Given the space constraints I don't think that would work on mobile though so if we do go for it on desktop I'd suggest we just hide the image at mobile breakpoints.

Thoughts?

**Comment by saschamt** [comment]
@willmot thanks Tom. I like the native look approach — we could use a smaller Mad Mimi image for the mobile layout, of just the logo copy, with a transparent background.

**Comment by willmot** [comment]
@saschamt makes sense! I'll experiment with a smaller logo on mobile 👍

**Comment by willmot** [comment]
@saschamt I actually switched things up a little after experimenting on mobile, I think it works best using the mad mimi women on a transparent background. What do you think:
![screen shot 2015-06-24 at 16 11 24](https://cloud.githubusercontent.com/assets/308507/8333709/2f198842-1a8c-11e5-9243-50ba800b3a96.png)
![screen shot 2015-06-24 at 16 11 30](https://cloud.githubusercontent.com/assets/308507/8333711/2ffae0a8-1a8c-11e5-99b9-be8a8c36c59a.png)

**Comment by saschamt** [comment]
Yep, nice Tom. Thanks!

**Comment by willmot** [comment]
Great, going with this then 👍
